### ISSUE TITLE
Add Feature: R markdown support

### ISSUE THREAD

**Issue by arielhasidim** [MichaelChirico/funchir#17]
There is not much to explain, but it will help and make life easier when trying to cite the packages in use when publishing an article.

Thank you!

**Comment by MichaelChirico** [comment]
Thanks for the interest Ariel!

Unfortunately I am not following -- where is RMarkdown support needed?

**Comment by arielhasidim** [comment]
Hello again, Michael!

I had this error when I tried to run this `funchir::stale_package_check('run_results.Rmd')`:
```
Failed to parse R script, please fix syntax errors first
  failed with: run_results.Rmd:18:1: unexpected '<'
17: ---
18: <
```
(line 18 begins with a comment like this "<-- @@ -->>").

That made me immediately think that Rmarkdown is not supported.

After seeing your reply, I tried to remove the comment and try again, this time with a new error and no pointer: `failed with: attempt to use zero-length variable name`. Checking this error led me to realize that the `stale_package_check` function tries to run all the mark down as a complete code and not look into the code chunks only ([ref1](https://stackoverflow.com/a/48795400/7224607), [ref2](https://rstudio-conf-2020.github.io/r-for-excel/rstudio.html#:~:text=Error%3A%20attempt%20to%20use%20zero%2Dlength%20variable%20name)).

**Comment by MichaelChirico** [comment]
Thanks again! I don't really plan to add support for Rmd since it will induce a {knitr} dependency I'd rather avoid.

If there is more interest I might reconsider and put knitr in Suggests, but I think the workaround is pretty straightforward:

```r
knitr::purl('run_results.Rmd', tmp<-tempfile())
funchir::stale_package_check(tmp)
```

BTW, I believe {lintr} also offers some similar functionality in [`unused_import_linter()`](https://lintr.r-lib.org/reference/unused_import_linter.html), you might check it out. {lintr} supports Rmd out of the box.

**Comment by arielhasidim** [comment]
It worked just fine, thank you!
